wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.16
    start_time: 1680762651.311608
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 15
      - 16
      - 23
      4: 3.7.16
      5: 0.14.0
      8:
      - 1
      - 3
      - 5
lr:
  desc: null
  value: 0.001
model_name:
  desc: null
  value: MLPWithDropout
optimizer_name:
  desc: null
  value: Adam
scheduler_name:
  desc: null
  value: WarmupLR
